In [1]:
import pandas as pd
import pywt
import numpy as np
import torch
import torch.nn as nn
from torch.nn.utils import weight_norm
from torch.utils.data import DataLoader
from tqdm.notebook import tqdm

use_cuda = torch.cuda.is_available()
device = torch.device("cuda" if use_cuda else "cpu")
#torch.backends.cudnn.benchmark = True

## Wavelet transform

In [2]:
def van_haar(data):
    ncol = data.shape[1]
    nrow = data.shape[0]
    for i in range(ncol):
        cur_col = data[:,i].copy()
        (cA, cD) = pywt.dwt(cur_col, 'haar')
        new_col = np.reshape(np.concatenate((cA,cD), 0),(nrow,1))
        data = np.hstack((data,new_col))
    data = data.reshape(nrow,-1)
    return data

#van_haar(test.to_numpy()).shape

## PyTorch

In [3]:
class Chomp1d(nn.Module):
    def __init__(self, chomp_size):
        super(Chomp1d, self).__init__()
        self.chomp_size = chomp_size

    def forward(self, x):
        return x[:, :, :-self.chomp_size].contiguous()

class TemporalBlock(nn.Module):
    def __init__(
            self, 
            n_inputs, 
            n_outputs, 
            kernel_size, 
            stride,
            dilation,
            padding,
            dropout=0.2):
        super(TemporalBlock, self).__init__()
        self.conv1 = weight_norm(
            nn.Conv1d(
                n_inputs, 
                n_outputs, 
                kernel_size,
                stride=stride, 
                padding=padding,
                dilation=dilation))
        self.pad = Chomp1d(padding)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(dropout)
        
        self.conv2 = weight_norm(
            nn.Conv1d(
                n_outputs, 
                n_outputs, 
                kernel_size,
                stride=stride, 
                padding=padding, 
                dilation=dilation))
        self.net = nn.Sequential(
            self.pad, 
            self.conv1, 
            self.relu, 
            self.dropout,
            self.pad, 
            self.conv2, 
            self.relu, 
            self.dropout)
        
        self.downsample = nn.Conv1d(
            n_inputs, n_outputs, 1) if n_inputs != n_outputs else None
        self.relu = nn.ReLU()
        self.init_weights()

    def init_weights(self):
        self.conv1.weight.data.normal_(0, 0.01)
        self.conv2.weight.data.normal_(0, 0.01)
        if self.downsample is not None:
            self.downsample.weight.data.normal_(0, 0.01)

    def forward(self, x):
        out = self.net(x)
        res = x if self.downsample is None else self.downsample(x)
        return self.relu(out + res)


class TemporalConvNet(nn.Module):
    def __init__(self, num_inputs, num_channels, kernel_size=2, dropout=0.2):
        super(TemporalConvNet, self).__init__()
        layers = []
        num_levels = len(num_channels)
        for i in range(num_levels):
            dilation_size = 2 ** i
            in_channels = num_inputs if i == 0 else num_channels[i-1]
            out_channels = num_channels[i]
            layers += [TemporalBlock(in_channels, 
                                     out_channels, 
                                     kernel_size, 
                                     stride=1, 
                                     dilation=dilation_size,
                                     padding=(kernel_size-1) * dilation_size, 
                                     dropout=dropout)]

        self.network = nn.Sequential(*layers)

    def forward(self, x):
        return self.network(x)

In [4]:
def reference_transform(tensor):
    array = tensor.numpy()
    out1, out2= pywt.dwt(array, "haar")
    out1 = torch.from_numpy(out1)
    out2 = torch.from_numpy(out2)
    
    #concatenate each channel to be able to concatenate it to the untransformed data
    #everything will then be split when fed to the network
    return torch.cat((out1, out2),-1)
    

In [5]:
class WaveletPart(nn.Module):

    def __init__(self, input_size, output_size):
        super(WaveletPart, self).__init__()

        # used two different layers here as in the paper but in the github code, they are the same
        self.fc1 = nn.Linear(input_size, output_size)
        self.fc2 = nn.Linear(input_size, output_size)

        self.input_size = input_size

        self.haar = reference_transform

    def init_weight(self):
        self.fc1.weight.data.normal_(0, 0.01)
        self.fc1.bias.data.normal_(0, 0.01)
        self.fc2.weight.data.normal_(0, 0.01)
        self.fc2.bias.data.normal_(0, 0.01)

    def forward(self, x):
        # split the wavelet transformed data along third dim
        x1, x2 = torch.split(x, 500, 2)

        # reshape everything to feed to the linear layer
        bsize = x.size()[0]
        x1 = self.fc1(x1.reshape((bsize, -1, 1)).squeeze())
        x2 = self.fc2(x2.reshape((bsize, -1, 1)).squeeze())
        x1 = x1.reshape(bsize, -1)
        x2 = x2.reshape(bsize, -1)
        return torch.cat((x1,x2),-1)

In [6]:
class Driver2Vec(nn.Module):
    def __init__(
            self, 
            input_size, 
            input_length, 
            num_channels,
            output_size, 
            kernel_size, 
            dropout,
            fc_output_size = 15):
        super(Driver2Vec, self).__init__()
        
        self.tcn = TemporalConvNet(input_size, 
                                   num_channels, 
                                   kernel_size=kernel_size, 
                                   dropout=dropout)
        
        self.haar = WaveletPart(input_size*input_length//2, fc_output_size)

        linear_size = num_channels[-1] + fc_output_size*2
        self.input_length = input_length

        self.input_bn = nn.LayerNorm(linear_size)
        self.linear = nn.Linear(linear_size, output_size)

    def forward(self, inputs):
        """Inputs have to have dimension (N, C_in, L_in*2)
        the base time series, and the two wavelet transform channel are concatenated along dim2"""
        
        # split the inputs, in the last dim, first is the unchanged data, then 
        # the wavelet transformed data
        input_tcn, input_haar = torch.split(inputs, self.input_length, 2)

        # feed each one to their corresponding network
        y1 = self.tcn(input_tcn)
        y1 = y1[:,:,-1] # for the TCN, only the last output element interests us
        y2 = self.haar(input_haar)

        concat = torch.cat((y1,y2),1)
        bsize = concat.shape[0]
        if bsize > 0: # issue when the batch size is 1, can't batch normalize it
            out = self.input_bn(concat)
        else:
            out = concat
        out = self.linear(out)
        
        return out

In [7]:
import os

def preprocess(df):
    return (
        df.drop(
            ["FOG",
             "FOG_LIGHTS",
             "FRONT_WIPERS",
             "HEAD_LIGHTS",
             "RAIN",
             "REAR_WIPERS",
             "SNOW",
            ], axis=1
        )
    )

def load_dataset(input_dir):
    x=[]
    y=[]
    for dir,_,files in os.walk(input_dir):
        for file in files:
            label = int(file.split("_")[1])
            df = pd.read_csv(dir + "/" + file, index_col=0)
            df = preprocess(df).to_numpy().transpose()
            x.append(torch.from_numpy(df).float())
            y.append(label)
    return x,y
        
class Dataset(torch.utils.data.Dataset):
    'Characterizes a dataset for PyTorch'
    def __init__(self, input_dir):
        'Initialization'
        self.data, self.labels = load_dataset(input_dir)
        self.index = [i for i in range(len(self.data))]

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        X_anchor = self.data[index]
        anchor_wvlt = reference_transform(X_anchor)
        y_anchor = self.labels[index]

        # create list of possible positive index samples
        positive_list = [
            i for i in self.index if self.labels[i] == y_anchor and i != index]
        positive_index = np.random.choice(positive_list)
        positive = self.data[positive_index]
        # get the wavelet transform of that sample (the two channels are concatenated along the last dim)
        positive_wvlt = reference_transform(positive)
        
        # same here
        negative_list = [
            i for i in self.index if self.labels[i] != y_anchor]
        negative_index = np.random.choice(negative_list)
        negative = self.data[negative_index]
        negative_wvlt = reference_transform(negative)

        # concatenate the data for the TCN and the haar wavelet transform
        # they will be split in the forward pass
        return torch.cat((X_anchor, anchor_wvlt),1), \
            torch.cat((positive, positive_wvlt),1), \
            torch.cat((negative, negative_wvlt),1), \
            y_anchor


In [8]:
input_channels = 31
channel_sizes = [32]
output_size = 62
kernel_size = 16
dropout = 0.1
model = Driver2Vec(input_channels, 1000, channel_sizes, output_size, kernel_size=kernel_size, dropout=dropout)
model.to(device)

Driver2Vec(
  (tcn): TemporalConvNet(
    (network): Sequential(
      (0): TemporalBlock(
        (conv1): Conv1d(31, 32, kernel_size=(16,), stride=(1,), padding=(15,))
        (pad): Chomp1d()
        (relu): ReLU()
        (dropout): Dropout(p=0.1, inplace=False)
        (conv2): Conv1d(32, 32, kernel_size=(16,), stride=(1,), padding=(15,))
        (net): Sequential(
          (0): Chomp1d()
          (1): Conv1d(31, 32, kernel_size=(16,), stride=(1,), padding=(15,))
          (2): ReLU()
          (3): Dropout(p=0.1, inplace=False)
          (4): Chomp1d()
          (5): Conv1d(32, 32, kernel_size=(16,), stride=(1,), padding=(15,))
          (6): ReLU()
          (7): Dropout(p=0.1, inplace=False)
        )
        (downsample): Conv1d(31, 32, kernel_size=(1,), stride=(1,))
      )
    )
  )
  (haar): WaveletPart(
    (fc1): Linear(in_features=15500, out_features=15, bias=True)
    (fc2): Linear(in_features=15500, out_features=15, bias=True)
  )
  (input_bn): LayerNorm((62,), eps=1

In [9]:

# datasets parameters
params = {'batch_size': 4,
          'shuffle': True,
          'num_workers': 1}
epochs = 50

training_set = Dataset("./dataset")
training_generator = DataLoader(training_set, **params)

loss = nn.TripletMarginLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [16]:
model.train()
for epoch in (pbar := tqdm(range(epochs))):
    loss_list = []
    for anchor, positive, negative, label in training_generator:
        print(label)
        anchor = anchor.to(device)
        positive = positive.to(device)
        negative = negative.to(device)

        y_anchor = model(anchor)
        y_positive = model(positive)
        y_negative = model(negative)

        loss_value = loss(y_anchor, y_positive, y_negative)
        loss_value.backward()

        optimizer.step()

        loss_list.append(loss_value.cpu().detach().numpy())
    print(anchor.cpu())
    #print("Epoch: {}/{} - Loss: {:.4f}".format(epoch+1, epochs, np.mean(loss_list)))
    pbar.set_description("Loss: %0.5g, Epochs" % np.mean(loss_list))



  0%|          | 0/50 [00:00<?, ?it/s]

tensor([2, 4, 3, 4])
tensor([5, 1, 4, 1])
tensor([2, 1, 2, 2])
tensor([5, 3, 5, 5])
tensor([3, 4, 1])
tensor([[[-1.8714e-01, -1.8183e-01, -1.6387e-01,  ..., -7.5239e-04,
          -6.4295e-04, -7.7929e-04],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 2.6295e-02,  2.8571e-02,  2.7789e-02,  ...,  2.3405e-03,
           5.1706e-03,  1.6385e-03],
         ...,
         [-2.0657e-03, -1.1659e-03, -8.8365e-04,  ...,  1.4067e-04,
           3.0425e-04,  1.3433e-04],
         [-2.8000e-02, -2.5012e-02, -2.4647e-02,  ..., -1.7413e-04,
          -8.1271e-05, -4.9442e-05],
         [-3.2838e-02, -3.3077e-02, -3.3317e-02,  ...,  8.4740e-04,
           1.8644e-03,  8.4741e-04]],

        [[-1.2293e-01, -1.2293e-01, -1.2293e-01,  ...,  0.0000e+00,
           4.5208e-06,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
           0.0000e+00,  0.0000e+00],
         [ 2.1874e-02,  2.1874e-02,  2.187

KeyboardInterrupt: 

In [13]:
import lightgbm as lgbm

params = {'batch_size': 1,
          'shuffle': False,
          'num_workers': 1}

classifier_set = Dataset("./dataset")
classifier_generator = DataLoader(training_set, **params)

x_train = []
y_train = []
for data,_, _, label in classifier_generator:

    data = data.to(device)
    embed = model(data)

    y = np.zeros(5, dtype=int)
    y[label-1] = 1

    x_train.append(embed.cpu().detach().numpy().squeeze())
    y_train.append(int(label)-1)

x_train = np.array(x_train)
y_train = np.array(y_train)

lgb_train = lgbm.Dataset(x_train, y_train)

params = {
    'boosting_type': 'gbdt',
    'objective': 'multiclass',
    'num_class':5,
    'metric': 'multi_logloss',
    'num_leaves': 31,
    'feature_fraction': 0.8,
    'bagging_fraction': 0.9,
    'max_depth': 12,
    'num_trees': 100,
    'verbose': 0
}

clf = lgbm.train(params,lgb_train)

[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] There are no meaningful features, as all feature values are constant.
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stop

/home/wslachille/.local/lib/python3.8/site-packages/lightgbm/engine.py:177: UserWarning: Found `num_trees` in params. Will use it instead of argument
  _log_warning(f"Found `{alias}` in params. Will use it instead of argument")


In [14]:
y_pred = clf.predict(x_train)
print(y_pred)

[[0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0.21052632 0.15789474 0.21052632 0.21052632]
 [0.21052632 0